firmware:
  image: antoinealb/gcc-arm-embedded
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install cvra-packager
    - git submodule update --init
    - packager
    - make

tests:
  image: antoinealb/cpputest
  script:
    - git submodule update --init
    - apt-get update && apt-get install -y cmake python3-pip
    - pip3 install cvra-packager
    - packager
    - mkdir build && pushd build
    - cmake ..
    - make check
    - popd
