dependency-dir: src

include_directories:
    - src/board
    - fatfs/src/

depends:
    - cmp_mem_access
    - pid
    - crc
    - parameter
    - serial-datagram
    - aseba_vm
    - chibios-syscalls

source:
    - src/cmp/cmp.c
    - fatfs/src/ff.c

target.arm:
    - src/panic.c
    - src/cmd.c
    - src/main.c
    - src/sensors/mpu60X0.c
    - src/sensors/proximity.c
    - src/sensors/imu.c
    - src/usbconf.c
    - src/exti.c
    - src/encoder.c
    - src/motor_pwm.c
    - src/board/board.c
    - src/analogic.c
    - src/control.c
    - src/pid_cascade.c
    - src/feedback.c
    - src/setpoints.c
    - src/sensors/vl6180x-driver/vl6180x.c
    - src/sensors/range.c
    - src/communication.c
    - src/datagram_dispatcher.c
    - src/attitude_estimation.c
    - src/segway.c
    - src/pose_estimation.c
    - src/memory_protection.c

templates:
    src/src.mk.jinja: 'src/src.mk'
