dependency-dir: src

include_directories:
    - src/board
    - fatfs/src/

depends:
    - cmp_mem_access
    - crc
    - parameter
    - aseba_vm
    - chibios-syscalls
    - msgbus
    - lwip
    - pid

source:
    - src/cmp/cmp.c
    - src/config_flash_storage.c
    - src/sensors/vl6180x/vl6180x.c
    - src/motor_controller.c

target.arm:
    - src/panic.c
    - src/cmd.c
    - src/main.c
    - src/sensors/mpu60X0.c
    - src/sensors/proximity.c
    - src/sensors/imu.c
    - src/sensors/motor_current.c
    - src/sensors/motor_pid_thread.c
    - src/usbconf.c
    - src/exti.c
    - src/encoder.c
    - src/motor_pwm.c
    - src/body_leds.c
    - src/board/board.c
    - src/sensors/range.c
    - src/sensors/battery_level.c
    - src/memory_protection.c
    - src/battery_protection.c
    - src/flash/flash.c
    - src/sensors/vl6180x/vl6180x_chibios.c
    - fatfs/src/ff.c
    - src/fatfs_diskio.c
    - src/fatfs_syscall.c
    - src/sdcard.c

tests:
    - tests/config_save_test.cpp
    - tests/flash_mock.cpp
    - tests/test_range_sensor.cpp
    - tests/motor_controller.cpp

templates:
    src/src.mk.jinja: 'src/src.mk'
