source:
  - lwip/src/core/def.c
  - lwip/src/core/dhcp.c
  - lwip/src/core/dns.c
  - lwip/src/core/inet_chksum.c
  - lwip/src/core/init.c
  - lwip/src/core/ipv4/autoip.c
  - lwip/src/core/ipv4/icmp.c
  - lwip/src/core/ipv4/igmp.c
  - lwip/src/core/ipv4/ip4.c
  - lwip/src/core/ipv4/ip4_addr.c
  - lwip/src/core/ipv4/ip_frag.c
  - lwip/src/core/ipv6/dhcp6.c
  - lwip/src/core/ipv6/ethip6.c
  - lwip/src/core/ipv6/icmp6.c
  - lwip/src/core/ipv6/inet6.c
  - lwip/src/core/ipv6/ip6.c
  - lwip/src/core/ipv6/ip6_addr.c
  - lwip/src/core/ipv6/ip6_frag.c
  - lwip/src/core/ipv6/mld6.c
  - lwip/src/core/ipv6/nd6.c
  - lwip/src/core/mem.c
  - lwip/src/core/memp.c
  - lwip/src/core/netif.c
  - lwip/src/core/pbuf.c
  - lwip/src/core/raw.c
  - lwip/src/core/snmp/asn1_dec.c
  - lwip/src/core/snmp/asn1_enc.c
  - lwip/src/core/snmp/mib2.c
  - lwip/src/core/snmp/mib_structs.c
  - lwip/src/core/snmp/msg_in.c
  - lwip/src/core/snmp/msg_out.c
  - lwip/src/core/stats.c
  - lwip/src/core/sys.c
  - lwip/src/core/tcp.c
  - lwip/src/core/tcp_in.c
  - lwip/src/core/tcp_out.c
  - lwip/src/core/timers.c
  - lwip/src/core/udp.c
  - lwip/src/api/api_lib.c
  - lwip/src/api/api_msg.c
  - lwip/src/api/err.c
  - lwip/src/api/netbuf.c
  - lwip/src/api/netdb.c
  - lwip/src/api/netifapi.c
  - lwip/src/api/sockets.c
  - lwip/src/api/tcpip.c

include_directories:
  - lwip/src/include
  - lwip/src/include/ipv4
